SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_2](
	[col1] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [idx_table_2_col1] ON [dbo].[Table_2]
(
	[col1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
